### ISSUE TITLE
Atualização dos arquivos referêntes a aula Contribuindo em um Projeto Open Souce

### ISSUE THREAD

**Issue by HudsonPeres** [elidianaandrade/dio-curso-git-github#10]
Na aula: Contribuindo em um Projeto Open Souce no GitHub, fala-se de um Guia de Contribuição (CONTRIBUTING.md), entretanto falta o aquivo, além disto o README.md parece estar desatualizado em relação com a aula.

**Comment by IvaldoLucasEN** [comment]
Olá; não encontrei o arquivo informado na vídeo aula. Conforme informado acima pelo usuário @HudsonPeres

**Comment by elidianaandrade** [comment]
Olá, @HudsonPeres e @IvaldoLucasEN! Vocês estão no repositório errado 😅
 Esse é referente ao curso Versionamento de Código com Git e GitHub. O repositório do lab é [dio-lab-open-source](https://github.com/elidianaandrade/dio-lab-open-source).
