### ISSUE TITLE
Atualizar repositório

### ISSUE THREAD

**Issue by Jademl27** [elidianaandrade/dio-curso-git-github#26]
E necessário atualizar o repositório no curso de git hub, pois não é esse o usado atualmente. se não for possivel atualizar no video, atualizar no material de estudo ou criar um tópico repositório com o link.

**Comment by elidianaandrade** [comment]
Olá @Jademl27! Esse repositório é o do Curso de Git e GitHub, o repositório do Desafio de Projeto é o [https://github.com/digitalinnovationone/dio-lab-open-source](https://github.com/digitalinnovationone/dio-lab-open-source). Ele está indicado em "Entendendo o Desafio" dentro da plataforma e fixado no meu perfil.
