### ISSUE TITLE
[SUGESTÃO] Adicionar o Guia de contribuição

### ISSUE THREAD

**Issue by Fsoares-1** [elidianaandrade/dio-curso-git-github#28]
Minha sugestão não esta relacionada a nenhum problema mas sugiro adicionar um README do Guia de contribuição, demostrando as melhores formar de contribuir no projeto, também identifiquei que todo o material que esta no Github está totalmente diferente das vídeos aulas na plataforma da DIO.

Eu estou iniciando o meu primeiro **BOOTCAMP Python AI Backend Developer** e alguns informações estão diferentes das vídeos aulas e acaba deixando quem está iniciando meio perdido no que fazer. Nunca tive contato com Git e Github ter um material atualizado ajuda muito no engajamento e na adesão do plano para continuar o aprendizado continuo com vocês.

**Comment by elidianaandrade** [comment]
Olá @Fsoares-1! Tudo bem? Esse repositório é referente ao **Curso** "Versionamento de Código com Git e GitHub", o repositório do **Desafio de Projeto** "Contribuindo em um Projeto Open Source no GitHub" é o [digitalinnovationone/dio-lab-open-source](https://github.com/digitalinnovationone/dio-lab-open-source), onde contém o [Guia de Contribuição](https://github.com/digitalinnovationone/dio-lab-open-source/blob/main/CONTRIBUTING.md).
