### ISSUE TITLE
Sugestão de conteúdo

### ISSUE THREAD

**Issue by jamcarvalho** [elidianaandrade/dio-curso-git-github#4]
bom dia, Eli,

Assistir à sua formação acerca do uso do GIT e GitHub e achei pouco didática a forma apresentada (não tome isso como crítica destrutiva). O que penso é que para um futuro desenvolvedor, parece uma coisa de outro mundo, altamente assustador (não é o meu caso, sou um desenvolvedor bastante experiente) e gostaria que esta formação fosse algo mais amigável para uma pessoa que esteja entrando no mundo de desenvolvimento de software, uma vez que esta formação é, praticamente, a porta de entrada no mundo do desenvolvimento. Tendo isso em conta, minha sugestão é: 

- Apresentar a interce gráfica do GIT como uma opção ao uso do Git/GitHub
![imagem1](https://github.com/elidianaandrade/dio-curso-git-github/assets/33987585/8c0bf1f1-bb2b-4f04-a81c-08b2001fb2f1)
![imagem2](https://github.com/elidianaandrade/dio-curso-git-github/assets/33987585/91367114-5883-47b2-8863-f6eda6f3fad8)

Acredito que para usuários menos experientes a interface gráfica seja muito mais amigável do que através de linhas de comando.

Espero ter contribuindo positivamente e estar ajudando.

forte abraço! :-)

**Comment by JBS387214** [comment]
Ajuda muito pois mostra passo a passo como deve ser feito.

**Comment by VanessaLNS** [comment]
Olá, Eli!

Estou iniciando essa jornada de aprendizado e concordo totalmente com o @jamcarvalho, fiquei muito perdida, ainda mais que é uma introdução obrigatória, para eu poder passar para um outro conteúdo que o objetivo não é ser Desenvolvedor. Vi que você comenta que é possível fazer de forma totalmente online (sem fazer downloads), e acho que fazer a apresentação de forma online seria muito importante.

**Comment by IvaldoLucasEN** [comment]
@jamcarvalho é meu caso sou novo na área e estou atualizado rota(busca de nova área) estou confuso haja vista que é muito processos, passos e informações.

**Comment by elidianaandrade** [comment]
Olá, Jam! Agradeço a sugestão! A respeito de um conteúdo focado nesses processos, indico encaminhar na DIO para que venha como demanda para algum instrutor, ou até mesmo criarem uma Formação de Git, pois o curso ao qual se refere a demanda foi explicar pelo terminal.
 A respeito do uso de GUI Clientes eu cito no curso, inclusive o GitHub Desktop, nos materiais de apoio para que a pessoa tenha conhecimento e possa pesquisar para saber mais, tendo em vista que não teria como abordar isso no curso, já que possui um limite de tempo.
 Ainda assim, acredito que mesmo os novos desenvolvedores devem se habituar com o uso do terminal. Acaba sendo uma "dor" necessária, pois todo processo de aprendizado gera desconforto. Eu também fiz transição de carreira como alguns alunos e comecei aprendendo Git do zero pelo terminal, então sei que no começo tudo pode parecer confuso, mas basta ter calma e praticar. Apesar disso, não trocaria o terminal no começo por aprender pela interface já que facilitou muito minha compreensão sobre outros processos também.
 O problema é que algumas pessoas querem soluções rápidas, principalmente em Bootcamps, focando apenas em terminar do que aprender durante o processo. Infelizmente as coisas não funcionam assim, principalmente se tratando de aprender algo novo. Requer prática, repetir processos, rever as aulas quantas vezes for necessário e pesquisar bastante.
