### ISSUE TITLE
Adicionar a convenção de commits no guia de contribuição 

### ISSUE THREAD

**Issue by Dan1e1rodrigues** [elidianaandrade/dio-curso-git-github#5]
1. Adicionar informações referentes a padronização das mensagens dos commits. 
2. Inserir uma tabela demostrando os tipos de commits a respeito de seu uso. 
3. Inserir as contribuições de forma mais estável. 
4. [link](https://github.com/Dan1e1rodrigues)
5. N/A

**Comment by sandrisleia** [comment]
Sugestão está relacionada a a um problema? Por Favor descreva.
Não

Descreva a solução que você gostaria.
Adicionar informações a padronização das mensagens dos commits no guia de contribuição

Descreva as alternativas que você considerou.
Inserir uma tabela demonstrando os tipos de commits e uma descrição a respeito de seu uso.

Contexto adicional.
N/A
